# Generated by Django 3.1.3 on 2021-04-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_post',
            name='myid',
            field=models.IntegerField(unique=True),
        ),
    ]
